apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
        - name: gcp-devops-gke
          image: gcr.io/learning-gcp-418416/gcpdevops
          ports:
            - containerPort: 5000
          env:
          - name: PORT
            value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gke-gcp-service
  namespace: gcp-devops-prod
  
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

